package:
  - path: /etc/bouncer-config.json
    content: |
      {
        "SUPERUSER_PASSWORD_HASH": "{{ superuser_password_hash }}",
        "SUPERUSER_USERNAME": "{{ superuser_username }}",
        "LOG_LEVEL_STDERR": "INFO",
        "AUTH_COOKIE_SECURE_FLAG": {{ auth_cookie_secure_flag }},
        "EXPIRATION_AUTH_TOKEN_DAYS": 5,
        "EXPIRATION_AUTH_COOKIE_DAYS": 4.5,
        "EXPIRATION_INFO_COOKIE_DAYS": 4.5,
        "DATASTORE_ZK_BACKEND_HOSTS": "127.0.0.1:2181",
        "GUNICORN_WORKER_PROCESSES": 1,
        "GUNICORN_THREADS_PER_WORKER": 10,
        "GUNICORN_BIND_ADDRESS": "127.0.0.1:8101",
        "GUNICORN_WORKER_TIMEOUT_SECONDS": 10
      }
  - path: /etc/dcos-signal-extra.json
    content: |
      {
        "customer_key": "{{ customer_key }}",
        "diagnostics_urls": [
            "https://leader.mesos/system/health/v1/report"
          ],
          "cosmos_urls": [
            "https://leader.mesos/package/list"
          ],
          "mesos_urls": [
            "https://leader.mesos/mesos/frameworks",
            "https://leader.mesos/mesos/metrics/snapshot"
          ],`
        "ca_cert_path": "/run/dcos/pki/CA/certs/ca.crt"
      }
  - path: /etc/mesos-slave-common-extras
    content: |
      MESOS_ISOLATION={{ mesos_isolation_modules }}
